title: Moksh Garg
logo: /assets/img/amb_spiceestew_2.png.jpg
description: PhD Candidate in Management at the MIT Sloan School of Management
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
